# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_creater',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_joiners',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to='book.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(related_name='items_wished', to='book.User'),
        ),
    ]
